Androapp 4925
Saudigitus/dhis2-android-capture-app pull request #18
Opened 2022-10-27 08:49 UTC by CarlosMacaneta

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://jira.dhis2.org/browse/

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [x] Smartphone Emulator
- [ ] Tablet Emulator
- [x] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [x] 8.X
- [ ] 9.X - 10.X
- [x] Other
## Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-10-27 12:19 UTC, mvmmacamo2 approved these changes

2022-11-02 06:58 UTC, Balcan requested changes

2022-11-02 06:58 UTC, Balcan commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt
> +                    MdcTheme {
In compose, the theme has to be the top element in the tree.
`setContent {
  MdcTheme{
    MainContent()
  }
}
`

2022-11-03 13:13 UTC, mvmmacamo2 requested changes
Make proceed button work as before or make it work for current table

2022-11-03 14:18 UTC, andresmr requested changes

2022-11-03 14:18 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt
> +        /*startActivity(
why is this commented?

2022-11-03 14:18 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
> +    private val _config = MutableLiveData(
I would not hardcore the values, could you send via parameters?

2022-11-04 08:56 UTC, CarlosMacaneta commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt
> +        /*startActivity(
resolved

2022-11-04 09:27 UTC, andresmr approved these changes

2022-11-04 13:00 UTC, andresmr approved these changes

2022-11-04 13:03 UTC, mvmmacamo2 approved these changes

2022-11-04 13:07 UTC, merged