Create UI states
Saudigitus/dhis2-android-capture-app pull request #41
Opened 2023-01-05 13:42 UTC by andresmr

2023-01-10 08:35 UTC, mvmmacamo2 requested changes

2023-01-10 09:47 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/HomeViewModel.kt
>          get() = _transactionDate
you are right, good feedback!. I'll do it.

2023-01-10 09:53 UTC, CarlosMacaneta approved these changes

2023-01-10 10:23 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt
> +                if (hasFacilitySelected) {
You are right, changing it...

2023-01-10 12:41 UTC, CarlosMacaneta commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/HomeViewModel.kt
>      private val _fromFacility = MutableStateFlow(UIText.StringRes(R.string.from_facility))
Why don't we move this to settingsuistate or create a toolbaruistate to listen this changes?

2023-01-11 06:41 UTC, mvmmacamo2 approved these changes

2023-01-11 08:35 UTC, CarlosMacaneta requested changes

2023-01-11 08:35 UTC, CarlosMacaneta commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/DropdownComponent.kt
>      val programUid = "F5ijs28K4s8"
why are we using hardcoded program uid?

2023-01-11 08:47 UTC, CarlosMacaneta approved these changes

2023-01-11 10:45 UTC, merged